version: "3"

services:
  db:
    image: postgres:11.6-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}

  redis:
    image: redis:5.0.7-alpine
    ports:
      - "127.0.0.1:6379:6379"

  mockcas:
    build: mockcas
    working_dir: /opt/app
    ports:
      - "127.0.0.1:${MOCKCAS_HOST_PORT}:${MOCKCAS_PORT}"
    environment:
      - DEVELOPMENT=${DEVELOPMENT}
      - PORT=${MOCKCAS_PORT}
    volumes:
      # Note that the package.json-like files were moved into the
      # container as specified by the elmclient/Dockerfile.
      - "./mockcas/src:/opt/app/src"
      - "./mockcas/run.sh:/opt/app/run.sh"
    entrypoint: "/opt/app/run.sh"

  todo:
    build: todo
    working_dir: /app
    entrypoint: /app/run.sh
    volumes:
      - ./todo:/app
    ports:
      - "8000:${TODO_PORT}"
    depends_on:
      - db
      - redis
      - mockcas
    links:
      - db:db
      - redis:redis
    environment:
      - PORT=${TODO_PORT}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      - DEVELOPMENT=${DEVELOPMENT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
